server:
  port: 9010

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-kafka-demo-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kafka.demo.amoeba.domain.RawTextDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.kafka.demo.amoeba.domain.RawTextSerializer